columbus-config:
  gs_bucket: tvlk-recsys-platform-storage
  final_avro_prefix: /traveloka/data/v1/final/avro/hour_1/
  final_avro_suffix: /**/*.avro
  pipeline_args:
    project: tvlk-recsys-platform
    job_name: ingestion-gcs-to-bigquery
    runner: DataflowRunner
    staging_location: gs://tvlk-recsys-platform-storage/staging
    temp_location: gs://tvlk-recsys-platform-storage/temp
    setup_file: ./setup.py
