experience:
  tables:
    - source_schema: edw
      table_name: fact_experience_search_experience
      columns:
        - event_id
        - cookie_id
        - session_id
        - event_dt
        - event_client_dt
        - profile_id
        - login_id
        - login_method
        - login_time
        - auth_level
        - machine_id
        - node_id
        - device_id
        - device_model
        - device_token
        - device_type
        - interface
        - os_version
        - app_version
        - country_id
        - language_id
        - locale_id
        - currency_id
        - ip
        - search_source
        - auto_complete_group_id
        - search_type
        - search_keyword
        - keyword_country
        - keyword_region
        - keyword_city
        - keyword_area
        - keyword_landmark
        - is_search_result_available
        - search_id
        - sort_selected
        - min_price
        - max_price
        - min_rating
        - max_rating
        - source
        - campaign
        - adgroup
        - keyword
        - last_paid_campaign
        - last_paid_channel
        - ad_location
        - last_ad_location
        - seo_page_category
        - last_paid_visit_month
        - utm_campaign
        - utm_medium
        - utm_source
        - utm_term
        - first_source
        - visit_count
        - modified_at
        - theme_filter
    - source_schema: edw
      table_name: fact_experience_search_ticket
      columns:
        - event_id
        - cookie_id
        - session_id
        - event_dt
        - event_client_dt
        - profile_id
        - login_id
        - login_method
        - login_time
        - auth_level
        - machine_id
        - node_id
        - device_id
        - device_model
        - device_token
        - device_type
        - interface
        - os_version
        - app_version
        - country_id
        - language_id
        - locale_id
        - currency_id
        - ip
        - search_id
        - product_country
        - product_region
        - product_city
        - product_area
        - product_landmark
        - provider_id
        - provider_name
        - supplier_id
        - supplier_name
        - experience_name
        - experience_type_id
        - experience_type
        - experience_themes_id
        - experience_themes
        - duration
        - transportation
        - rating
        - total_reviewers
        - original_purchase_fare_per_pax_adult
        - purchase_fare_per_pax_adult
        - normal_fare_per_pax_adult
        - sales_fare_per_pax_adult
        - original_purchase_fare_currency_id
        - pricing_id
        - pricing_name
        - enterance_date
        - num_adult
        - num_child
        - first_source
        - visit_count
        - source
        - campaign
        - adgroup
        - keyword
        - last_paid_campaign
        - last_paid_channel
        - ad_location
        - last_ad_location
        - seo_page_category
        - last_paid_visit_month
        - utm_campaign
        - utm_medium
        - utm_source
        - utm_term
        - modified_at
        - conversion_rate_id
        - experience_id
    - source_schema: edw
      table_name: fact_experience_select_experience
      columns:
        - event_id
        - cookie_id
        - session_id
        - event_dt
        - event_client_dt
        - profile_id
        - login_id
        - login_method
        - login_time
        - auth_level
        - machine_id
        - node_id
        - device_id
        - device_model
        - device_token
        - device_type
        - interface
        - os_version
        - app_version
        - country_id
        - language_id
        - locale_id
        - currency_id
        - ip
        - search_id
        - search_keyword
        - product_country
        - product_region
        - product_city
        - product_area
        - product_landmark
        - provider_id
        - provider_name
        - supplier_id
        - supplier_name
        - experience_name
        - experience_type_id
        - experience_type
        - experience_themes_id
        - experience_themes
        - duration
        - transportation
        - rating
        - total_reviewers
        - original_purchase_fare_per_pax_adult
        - purchase_fare_per_pax_adult
        - normal_fare_per_pax_adult
        - sales_fare_per_pax_adult
        - original_purchase_fare_currency_id
        - pricing_id
        - pricing_name
        - first_source
        - visit_count
        - source
        - campaign
        - adgroup
        - keyword
        - last_paid_campaign
        - last_paid_channel
        - ad_location
        - last_ad_location
        - seo_page_category
        - last_paid_visit_month
        - utm_campaign
        - utm_medium
        - utm_source
        - utm_term
        - modified_at
        - conversion_rate_id
        - experience_id
    - source_schema: edw
      table_name: fact_experience_select_ticket
      columns:
        - event_id
        - cookie_id
        - session_id
        - event_dt
        - event_client_dt
        - profile_id
        - login_id
        - login_method
        - login_time
        - auth_level
        - machine_id
        - node_id
        - device_id
        - device_model
        - device_token
        - device_type
        - interface
        - os_version
        - app_version
        - country_id
        - language_id
        - locale_id
        - currency_id
        - ip
        - search_id
        - product_country